import {
  Server,
  Database,
  Monitor,
  Shield,
  Scale,
  MessageSquare,
  Zap,
  Cloud,
  HardDrive,
  Cpu,
  Globe,
  ExternalLink,
  Square,
  Circle,
  Minus,
  ArrowRight,
  MoreHorizontal,
  User,
  Cylinder,
  Triangle,
  type LucideIcon,
  Component,
  Code,
  RectangleCircle,
  PackageOpen,
} from 'lucide-react';
import type { NodeType } from './types';

export interface PaletteItem {
  type: NodeType;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
  bgColor: string;
  borderColor: string;
  group: 'cloud' | 'shape' | 'c4';
}

/** Node types that represent lines/connectors — no drill-down option */
export const LINE_NODE_TYPES = new Set<string>(['line', 'arrowline', 'dottedline']);

export const PALETTE_ITEMS: PaletteItem[] = [
  // ── Cloud Services ──────────────────────────────────────────────────────────
  {
    type: 'service',
    label: 'Service',
    description: 'Microservice or backend',
    icon: Server,
    color: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    group: 'cloud',
  },
  {
    type: 'database',
    label: 'Database',
    description: 'SQL, NoSQL, data store',
    icon: Database,
    color: 'text-green-700',
    bgColor: 'bg-green-50',
    borderColor: 'border-green-300',
    group: 'cloud',
  },
  {
    type: 'client',
    label: 'Client',
    description: 'Browser, mobile, CLI',
    icon: Monitor,
    color: 'text-purple-700',
    bgColor: 'bg-purple-50',
    borderColor: 'border-purple-300',
    group: 'cloud',
  },
  {
    type: 'gateway',
    label: 'API Gateway',
    description: 'Entry point / router',
    icon: Shield,
    color: 'text-orange-700',
    bgColor: 'bg-orange-50',
    borderColor: 'border-orange-300',
    group: 'cloud',
  },
  {
    type: 'loadbalancer',
    label: 'Load Balancer',
    description: 'Traffic distribution',
    icon: Scale,
    color: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
    group: 'cloud',
  },
  {
    type: 'queue',
    label: 'Message Queue',
    description: 'Kafka, RabbitMQ, SQS',
    icon: MessageSquare,
    color: 'text-yellow-700',
    bgColor: 'bg-yellow-50',
    borderColor: 'border-yellow-300',
    group: 'cloud',
  },
  {
    type: 'cache',
    label: 'Cache',
    description: 'Redis, Memcached, CDN',
    icon: Zap,
    color: 'text-cyan-700',
    bgColor: 'bg-cyan-50',
    borderColor: 'border-cyan-300',
    group: 'cloud',
  },
  {
    type: 'group',
    label: 'Cloud Group',
    description: 'AWS, GCP, Azure zone',
    icon: Cloud,
    color: 'text-slate-700',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
    group: 'cloud',
  },
  {
    type: 'storage',
    label: 'Object Storage',
    description: 'S3, GCS, Azure Blob',
    icon: HardDrive,
    color: 'text-indigo-700',
    bgColor: 'bg-indigo-50',
    borderColor: 'border-indigo-300',
    group: 'cloud',
  },
  {
    type: 'serverless',
    label: 'Serverless',
    description: 'Lambda, Cloud Functions',
    icon: Cpu,
    color: 'text-rose-700',
    bgColor: 'bg-rose-50',
    borderColor: 'border-rose-300',
    group: 'cloud',
  },
  {
    type: 'cdn',
    label: 'CDN',
    description: 'CloudFront, Fastly, Cloudflare',
    icon: Globe,
    color: 'text-teal-700',
    bgColor: 'bg-teal-50',
    borderColor: 'border-teal-300',
    group: 'cloud',
  },
  {
    type: 'external',
    label: 'External API',
    description: 'Third-party service or API',
    icon: ExternalLink,
    color: 'text-slate-600',
    bgColor: 'bg-slate-100',
    borderColor: 'border-slate-400',
    group: 'cloud',
  },

  // ── Shapes ──────────────────────────────────────────────────────────────────
  {
    type: 'rectangle',
    label: 'Rectangle',
    description: 'Generic box / container',
    icon: Square,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-400',
    group: 'shape',
  },
  {
    type: 'circle',
    label: 'Circle',
    description: 'Round shape',
    icon: Circle,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-400',
    group: 'shape',
  },
  {
    type: 'ellipse',
    label: 'Ellipse',
    description: 'Oval shape',
    icon: Circle,
    color: 'text-slate-600',
    bgColor: 'bg-slate-50',
    borderColor: 'border-slate-300',
    group: 'shape',
  },
  {
    type: 'line',
    label: 'Line',
    description: 'Plain horizontal line',
    icon: Minus,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-300',
    group: 'shape',
  },
  {
    type: 'arrowline',
    label: 'Arrow Line',
    description: 'Line with arrowhead',
    icon: ArrowRight,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-300',
    group: 'shape',
  },
  {
    type: 'dottedline',
    label: 'Dotted Line',
    description: 'Dashed / dotted line',
    icon: MoreHorizontal,
    color: 'text-slate-600',
    bgColor: 'bg-white',
    borderColor: 'border-slate-300',
    group: 'shape',
  },
  {
    type: 'actor',
    label: 'Actor',
    description: 'UML user / actor',
    icon: User,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-400',
    group: 'shape',
  },
  {
    type: 'cylinder',
    label: 'Cylinder',
    description: 'Drum / storage shape',
    icon: Cylinder,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-400',
    group: 'shape',
  },
  {
    type: 'triangle',
    label: 'Triangle',
    description: 'Triangular shape',
    icon: Triangle,
    color: 'text-slate-700',
    bgColor: 'bg-white',
    borderColor: 'border-slate-400',
    group: 'shape',
  },
  {
    type: 'systemcontext',
    label: 'System Context',
    description: 'High-level System Context view how it interacts with users and other systems (e.g., APIs, databases).',
    icon: RectangleCircle,
    color: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    group: 'c4',
  },
  {
    type: 'container',
    label: 'Container',
    description: 'High-level architecture view of Web applications, mobile apps, databases, and microservices',
    icon: PackageOpen,
    color: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    group: 'c4',
  },
  {
    type: 'component',
    label: 'Component',
    description: 'Breaks down each container into its components (e.g., controllers, services)',
    icon: Component,
    color: 'text-blue-700',
    bgColor: 'bg-blue-50',
    borderColor: 'border-blue-300',
    group: 'c4',
  },
  {
    type: 'code',
    label: 'Code',
    description: 'The lowest level, detailing how components are implemented, typically showing class diagrams or code structures.',
    icon: Code,
    color: 'text-red-700',
    bgColor: 'bg-red-50',
    borderColor: 'border-red-300',
    group: 'c4',
  },
];
